560:: feat: integration test with check pin method which need logic improve…
Tonomy-Foundation/Tonomy-ID-SDK pull request #186
Opened 2023-03-24 10:06 UTC by HaseebUllahAbbasi

2023-03-24 13:40 UTC, theblockstalk requested changes
missing integration tests

2023-03-24 13:40 UTC, theblockstalk commented on src/user.ts
> +        const onchainKey = accountData.getPermission('owner').required_auth.keys[0].key;
should check pin permission, not owner

2023-03-24 13:40 UTC, theblockstalk commented on src/user.ts
> +        // console.log('Pin Key', pinKey?.toString());
remove unused comments

2023-03-24 14:08 UTC, HaseebUllahAbbasi commented on src/user.ts
> +        const onchainKey = accountData.getPermission('owner').required_auth.keys[0].key;
changed to pin

2023-03-24 14:08 UTC, HaseebUllahAbbasi commented on src/user.ts
> +        // console.log('Pin Key', pinKey?.toString());
removed

2023-03-27 15:03 UTC, theblockstalk reviewed
we discussed yesterday that you would modify KeyManager.getKey() to have optional input `challenge` in the GetKeyOptions
challenge is compared against the salted hashed challenge

this then needs to be updated in all the implementations of the KeyManager, and their consumers

2023-03-27 15:03 UTC, theblockstalk commented on test-integration/user.test.ts
> +            await expect(user.checkPassword(password)).resolves.toBe(true);
no need for L331 if you have L332

2023-03-27 15:03 UTC, theblockstalk commented on src/user.ts
> +        const username = await this.getAccountName();
don't need to check the on-chain key, only the one in keyStorage

2023-03-28 09:52 UTC, theblockstalk requested changes
are there any instances of keyManager in Tonomy ID or App Websites, or where these keyManager instances are consumed that need updating?

2023-03-28 10:28 UTC, HaseebUllahAbbasi commented on test/services/jskeymanager.ts
> +            if (options?.challenge) {
sure Adding

2023-03-28 11:50 UTC, theblockstalk commented
these two lines need updating to send in the challenge
https://github.com/Tonomy-Foundation/Tonomy-ID-SDK/blob/development/src/user.ts#L185
https://github.com/Tonomy-Foundation/Tonomy-ID-SDK/blob/development/src/user.ts#L235
https://github.com/Tonomy-Foundation/Tonomy-ID-SDK/blob/development/src/user.ts#L270
https://github.com/Tonomy-Foundation/Tonomy-ID-SDK/blob/development/src/user.ts#L348

because of the above, the createPerson(), updateKeys(), checkPassword(), login(), checkKeysStillValid() functions would need to be updated to have the password/pin challenge sent in - in the tests as well as consumers of these function in TID and App Websites.

we should discuss this approach more.

2023-03-28 12:02 UTC, theblockstalk commented on test/services/jskeymanager.ts
> +            if (options.level === KeyManagerLevel.PIN) {
remove this challenge guarde completly

2023-03-28 12:03 UTC, theblockstalk commented on test/services/jskeymanager.ts
> +            if (options.level === KeyManagerLevel.PIN) {
https://github.com/Tonomy-Foundation/Tonomy-ID/issues/396

2023-03-28 12:06 UTC, theblockstalk commented on test/services/jskeymanager.ts
> +            if (options.level === KeyManagerLevel.PIN) {
ok, as discussed. we will create a new function on the KeyManager
`checkKey(keyManagerLevel: KeyManagerLevel, challenge): Promise<boolean>`
which gets implemented in the instances (tests, TID and App Websites) to check if the challenge is correct

2023-03-28 12:08 UTC, theblockstalk commented on test/services/jskeymanager.ts
> +            if (options.level === KeyManagerLevel.PIN) {
this is used in checkPin()

2023-03-29 09:17 UTC, theblockstalk commented on src/services/keymanager.ts
> +    challenge?: string;
get key doesnt require challenge, check key does

```ts
type GetKeyOptions = {
    level: KeyManagerLevel;
};
type CheckKeyOptions = {
    level: KeyManagerLevel;
    challenge: string;
};
```

2023-03-29 09:17 UTC, theblockstalk commented on src/services/keymanager.ts
> +     * @throws if challenge is not provided or not matched
@throws if challenge is not provided

2023-03-29 09:17 UTC, theblockstalk commented on src/services/keymanager.ts
> +     * @param Options for checking key with level, and challenge
show type and variable name like:
@param options {GetKeyOption} - 

also add a typedef to GetKeyOption

https://devhints.io/jsdoc

2023-03-29 09:55 UTC, theblockstalk commented on test/services/jskeymanager.ts
> +                else throw throwError('Pin is incorrect', SdkErrors.PinInValid);
this should return false

2023-03-29 10:03 UTC, theblockstalk approved these changes

2023-03-29 12:42 UTC, merged

2023-03-29 12:43 UTC, theblockstalk commented
:tada: This PR is included in version 0.3.20 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@tonomy/tonomy-id-sdk/v/0.3.20)
- [GitHub release](https://github.com/Tonomy-Foundation/Tonomy-ID-SDK/releases/tag/0.3.20)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: